[package]
name = "wtransport"
version = "0.1.4"
license = "MIT OR Apache-2.0"
authors = ["Biagio Festa"]
description = "Implementation of the WebTransport (over HTTP3) protocol"
repository = "https://github.com/BiagioFesta/wtransport"
keywords = ["webtransport"]
categories = [ "network-programming", "asynchronous" ]
edition = "2021"
readme = "../README.md"
workspace = ".."
rust-version = "1.64.0"

[[example]]
name = "client"
required-features = ["dangerous-configuration"]

[dependencies]
bytes = "1.4.0"
quinn = "0.10.1"
quinn-proto = "0.10.1"
rustls = "0.21.1"
rustls-native-certs = "0.6.2"
rustls-pemfile = "1.0.2"
socket2 = "0.5.3"
thiserror = "1.0.40"
tokio = { version = "1.28.1", default-features = false, features = ["macros"] }
tracing = "0.1.37"
url = "2.4.0"
wtransport-proto = { version = "0.1.4", path = "../wtransport-proto", features = ["async"] }

[dev-dependencies]
anyhow = "1.0.71"
base64 = "0.21.0"
rcgen = "0.10.0"
ring = "0.16.20"
time = "0.3.21"
tokio = { version = "1.28.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
default = []
dangerous-configuration = ["rustls/dangerous_configuration"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
