name: MSRV

on:
  schedule:
    - cron: "0 9,18 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: cargo install cargo-msrv --locked
      - name: Msrv WTransport-Proto
        run: cargo msrv --path wtransport-proto --output-format json find
      - name: Msrv WTransport
        run: cargo msrv --path wtransport --output-format json find
      - name: Msrv Check WTransport-Proto
        run: cargo msrv --path wtransport-proto --output-format json --log-level trace verify
      - name: Msrv Check WTransport
        run: cargo msrv --path wtransport --output-format json --log-level trace verify
